// <auto-generated />
namespace EntityFrameworkPractice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedFirstNameandLastNametoStudentstable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedFirstNameandLastNametoStudentstable));
        
        string IMigrationMetadata.Id
        {
            get { return "201805090135031_added FirstName and LastName to Students table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
